from applic.extensions import mm
from testrun.role.model import Role

class RoleSchema( mm.ModelSchema ):
    """Schema for the role table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    class Meta:
        model = Role

roleSchema   = RoleSchema()
rolesSchema  = RoleSchema( many = True )
