# Generated by gencrud
# field tracking.T_ACTION constants
C_T_ACTION_INSERT                                             = 1
C_T_ACTION_UPDATE                                             = 2
C_T_ACTION_DELETE                                             = 3

C_T_ACTION_MAPPING = {1: 'Insert', 2: 'Update', 3: 'Delete'}


