LOGGING_COMMON: &logging
    version: 1
    formatters: &logging_formatters
        default:
            format: "[%(asctime)s] %(levelname)s %(name)s in %(module)s.%(funcName)s( %(lineno)s ): %(message)s"

        console:
            format: "%(asctime)s %(levelname)s %(name)s in %(module)s: %(message)s"

    handlers: &logging_handlers
        console: &logging_handler_console
            class: logging.StreamHandler
            stream: ext://sys.stdout
            formatter: console
            level: DEBUG

        logfile: &logging_handler_logfile
            class: logging.handlers.RotatingFileHandler
            filename: webapp.log
            maxBytes: 10485760
            backupCount: 7
            formatter: default
            level: DEBUG

    loggers: &logging_loggers
        flask.app:
            level: DEBUG

        webapp:
            level: DEBUG

    root: &logging_root
        level: DEBUG
        handlers:
        -   console
        -   logfile

COMMON: &common
    SECRET_KEY:                         insecure
    HOST:                               0.0.0.0
    PORT:                               8000
    DEBUG:                              false
    TESTING:                            false
    API_MODULE:                         application
    LOGGING:
        <<: *logging
        handlers:
            <<: *logging_handlers
            logfile:
                <<: *logging_handler_logfile
                filename: /var/log/dev/webapp.log
    APP_PATH:                           /opt/application
    ANGULAR_PATH:                       ./frontend/dist/angular-app
    BCRYPT_LOG_ROUNDS:                  13
    DEBUG_TB_INTERCEPT_REDIRECTS:       false
    CACHE_TYPE:                         simple
    SQLALCHEMY_TRACK_MODIFICATIONS:     false
    JWT_AUTH_USERNAME_KEY:              id
    JWT_AUTH_HEADER_PREFIX:             Authorization
    JWT_HEADER_TYPE:                    JWT
    JWT_EXPIRATION_DELTA:               weeks=52
    ACCESS_TOKEN_EXPIRES:               days=365
    ALLOW_CORS_ORIGIN:                  false
    CORS_ORIGIN_WHITELIST: []
    SQLALCHEMY_POOL_RECYCLE:            28799
DATABASE:   &database
    ENGINE:                             mysql+pymysql
    HOST:                               localhost
    PORT:                               3306

DEVELOPMENT:    &development
    <<: *common
    DEBUG:                          true
    TESTING:                        true
    PORT:                           8000
    ENV:                            dev
    APP_PATH:                       ~/src/python/application
    ANGULAR_PATH:                   ./frontend/dist/angular-app
    LOGGING:
        <<: *logging
        handlers:
            <<: *logging_handlers
            logfile:
                <<: *logging_handler_logfile
                filename: ~/log/webapp.log
    DATABASE:
        <<: *database
        SCHEMA:                     schema
        USERNAME:                   username
        PASSWORD:                   password

STAGING:
    <<: *common
    SECRET_KEY:                     sortasecure
    ENV:                            staging
    DEBUG:                          true
    TESTING:                        true
    LOGGING:
        <<: *logging
        handlers:
            <<: *logging_handlers
            logfile:
                <<: *logging_handler_logfile
                filename: /var/log/staging/webapp.log
    DATABASE:
        <<: *database
        SCHEMA:                     schema
        USERNAME:                   username
        PASSWORD:                   password

PRODUCTION:
    <<: *common
    SECRET_KEY:                     shouldbereallysecureatsomepoint
    PORT:                           80
    LOGGING:
        <<: *logging
        handlers:
            <<: *logging_handlers
            logfile:
                <<: *logging_handler_logfile
                filename: /var/log/prod/webapp.log
    ENV:                            prod
    DATABASE:
        <<: *database
        SCHEMA:                     schema
        USERNAME:                   username
        PASSWORD:                   password
