#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation; either version 2 of the
#   License, or (at your option) any later version.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   Frontend view for the ${ obj.name } table, this is generated by the
#   gencrud.py module. When modifing the file make sure that you remove
#   the table from the configuration.
#
import os
from pytemplate.objects.object import TemplateObject
from pytemplate.source import TemplateSource
from pytemplate.util.folders import findpath
from pytemplate.util.exceptions import MissingSourceFolder

class TemplateConfiguration( object ):
    def __init__( self, **cfg ):
        self.__config   = cfg
        current_path = os.getcwd()
        python_path = cfg[ 'source' ][ 'python' ]
        angular_path = cfg[ 'source' ][ 'angular' ]
        if python_path.startswith( '.' ) and angular_path.startswith( '.' ):
            if current_path.endswith( python_path[1:] ):
                # We are on the python folder
                current_path = findpath( angular_path )

                pass

            elif current_path.endswith( angular_path[1:] ):
                # We are on the Angular folder
                current_path = findpath( python_path )

            elif ( os.path.isdir( os.path.join( current_path, python_path ) ) and
                   os.path.isdir( os.path.join( current_path, angular_path ) ) ):
                # we are on the project root folder
                pass

            else:
                raise MissingSourceFolder( python_path, angular_path )

        else:
            if os.path.isdir( python_path ) and os.path.isdir( angular_path ):
                # We have a full path and they exist
                pass

            else:
                raise MissingSourceFolder( python_path, angular_path )

        self.__python   = TemplateSource( 'python', current_path, **self.__config )
        self.__angular  = TemplateSource( 'angular', current_path, **self.__config )
        self.__objects  = []
        for obj in cfg[ 'objects' ]:
            #print( obj )
            self.__objects.append( TemplateObject( **obj ) )

        return

    @property
    def python( self ):
        return self.__python

    @property
    def angular( self ):
        return self.__angular

    @property
    def objects( self ):
        return self.__objects

    def __iter__( self ):
        return iter( self.__objects )

    @property
    def application( self ):
        return self.__objects[ 0 ].application
