#!/usr/bin/python3
#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation; either version 2 of the
#   License, or (at your option) any later version.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   Frontend view for the ${ obj.name } table, this is generated by the
#   gencrud.py module. When modifing the file make sure that you remove
#   the table from the configuration.
#
from __future__ import print_function    # (at top of module)
import getopt
import json
import yaml
import os
import sys
import glob
import traceback
import logging
import pytemplate.util.utils
from pytemplate.configuraton import TemplateConfiguration
from pytemplate.generators.python import generatePython
from pytemplate.generators.angular import generateAngular
from pytemplate.version import __version__, __author__, __email__, __copyright__
from pytemplate.util.exceptions import ( InvalidEnvironment,
                                         EnvironmentInvalidMissing,
                                         MissingAngularEnvironment,
                                         FlaskEnvironmentNotFound,
                                         ModuleExistsAlready,
                                         InvalidSetting )

logger = logging.getLogger()


def verifyLoadProject( env, config ):
    if env == 'angular':
        configFile  = os.path.join( '..', '..', 'angular.json' )
        root        = config.angular

    elif env == 'python':
        configFile  = 'config.json'
        root = config.python

    else:
        raise InvalidEnvironment( env )

    if os.path.isdir( root.sourceFolder ) and os.path.isfile( os.path.join( root.sourceFolder, configFile ) ):
        with open( os.path.join( root.sourceFolder, configFile ), pytemplate.util.utils.C_FILEMODE_READ ) as stream:
            data = json.load( stream )

        if data is None:
            raise EnvironmentInvalidMissing( env, root.sourceFolder, configFile )

    else:
        raise EnvironmentInvalidMissing( env, root.sourceFolder, configFile )

    logger.info( 'Configuration for {}: {}'.format( env, json.dumps( data, indent = 4 ) ) )
    if env == 'angular':
        # Check if we have a valid Angular environment
        if 'defaultProject' in data and 'projects' in data:
            if data[ 'defaultProject' ] not in data[ 'projects' ]:
                raise MissingAngularEnvironment( '{} projects'.format( data[ 'defaultProject' ] ) )

            else:
                data = data[ 'projects' ][ data[ 'defaultProject' ] ]

        else:
            raise MissingAngularEnvironment( 'tag defaultProject' )

    elif env == 'python':
        # Check if we have a valid Python-Flask environment
        if not ( 'COMMON' in data and 'API_MODULE' in data[ 'COMMON' ] ):
            raise FlaskEnvironmentNotFound()

        logging.info( "Application: {} target application: {}".format( config.application, data[ 'COMMON' ][ 'API_MODULE' ] ) )
        if data[ 'COMMON' ][ 'API_MODULE' ] != config.application:
            raise FlaskEnvironmentNotFound()

    return data


def doWork( inputFile ):
    with open( inputFile, 'r' ) as stream:
        config = TemplateConfiguration( **yaml.load( stream ) )

    verifyLoadProject( 'angular', config )
    verifyLoadProject( 'python', config )
    generatePython( [ os.path.abspath( os.path.join( config.python.templateFolder, t ) )
                                   for t in os.listdir( config.python.templateFolder ) ],
                    config )
    generateAngular( [ os.path.abspath( os.path.join( config.angular.templateFolder, t ) )
                                    for t in os.listdir( config.angular.templateFolder ) ],
                     config )
    return


def banner():
    print( '''gencrud - Python backend and Angular frontend code generation, version {version}
Copyright (C) {copyright} {autor} <{email}>
'''.format( version = __version__, autor = __author__, email = __email__, copyright = __copyright__ ) )

def usage( msg = '' ):
    banner()
    if msg != '':
        print( "{msg}\n".format( msg = msg ), file = sys.stderr )

    print( '''
Syntax:
    gencrud [options] [input-file1 ... input-fileN]

Parameters:


Options:
    -h / --help                         This help information.
    -b / --backup                       Make backup of the orginal project files files.
    -o / --overwrite                    Force overwriting the files.
    -c / --case-insensitive-db-ids      All database names shall be in lower case. 
    -s / --sslverify                    Disable the verification of ssl certificate when    
                                        retrieving some external profile data.
    -v                                  Verbose option, prints what the tool is doing.
    -V / --version                      Print the version of the tool.
''' )
    return


def main():
    FORMAT = '%(levelname)s %(message)s'
    logging.basicConfig( format = FORMAT, level=logging.WARNING, stream = sys.stdout )
    try:
        opts, args = getopt.getopt( sys.argv[1:],
                                    'hi:s:obvVc', [ 'help',
                                                    'input=',
                                                    'sslverify=',
                                                    'overwrite',
                                                    'backup'
                                                    'version',
                                                    'case-insensitive-db-ids' ] )

    except getopt.GetoptError as err:
        # print help information and exit:
        usage( str( err ) )
        sys.exit( 2 )

    try:
        for o, a in opts:
            if o == '-v':
                if logger.level == logging.WARNING:
                    logger.setLevel( logging.INFO )

                else:
                    logger.setLevel( logging.DEBUG )

            elif o in ( '-h', '--help' ):
                usage()
                sys.exit()

            elif o in ( '-b', '--backup' ):
                pytemplate.util.utils.backupFiles = True

            elif o in ( '-c', '--case-insensitive-db-ids' ):
                pytemplate.util.utils.lowerCaseDbIds = True

            elif o in ( '-o', '--overwrite' ):
                pytemplate.util.utils.overWriteFiles = True

            elif o in ('-V', '--version'):
                print( '{0}'.format( __version__ ) )
                sys.exit()

            elif o.lower() in ( '-s', '--sslverify' ):
                pytemplate.util.utils.sslVerify = a.lower( ) == 'true'

            else:
                assert False, 'unhandled option'

        pytemplate.util.utils.check_nltk( )
        if len( args ) == 0:
            usage( 'Missing input file(s)' )
            sys.exit( 1 )

        banner()
        for arg in args:
            if '*' in arg:
                # Wild card handling
                for filename in glob.glob( os.path.abspath( os.path.expanduser( arg ) ) ):
                    if filename.lower().endswith( '.yaml' ):
                        print( filename )
                        doWork( filename )


            else:
                doWork( arg )

        print( "Done" )

    except ModuleExistsAlready as exc:
        logger.error( 'Module already exists: {}'.format( str( exc ) ) )
        logger.error( 'You can use the --overwrite option to avoid this error.' )

    except InvalidSetting as exc:
        logger.error( "Invalid setting" )
        logger.error( str( exc ) )

    except FileNotFoundError as exc:
        logger.error( "File not found" )
        if exc.filename in args:
            logger.error( "Input file '{0}' is not found.".format( exc.filename ) )

        else:
            logger.debug( traceback.format_exc() )
            logger.error( exc )

    except Exception as exc:
        logger.error( "Exception" )
        logger.debug( traceback.format_exc() )
        logger.error( exc )

    return


if __name__ == '__main__':
    if sys.version_info.major >= 3 and sys.version_info.minor >= 5:
        main()

    else:
        banner()
        print( "Error: This script runs with Python 3.5 or higher.")
