#
#   Python backend and Angular frontend code generation by gencrud
#   installer for the default environment of gencrud into a project
#   Copyright (C) 2018-2023 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
from typing import Union
import os
import shutil

# Standard target path(s)
#   templates
#       gencrud-v<version>
#           angular
#               ...
#           common
#               angular
#                   ...
#               python
#                   ...
#           python
#               ...
#       defaults
#           defaults.yaml
#           action-no-add.yaml
#           action-no-edit.yaml
#           action-no-delete.yaml
#           action-default-add.yaml
#           action-default-edit.yaml
#           action-default-delete.yaml
#       example-application.templ


def myCopyFile( src, dst, *, follow_symlinks=True ):
    print( f"Copy {src} to {dst}" )
    shutil.copy2( src, dst, follow_symlinks=follow_symlinks )
    return


def copyTemplates( source: str, target: str, overwrite = False ):
    shutil.copytree( source, target, dirs_exist_ok = overwrite, copy_function = myCopyFile )
    return


def __writeFileData( writer, data: Union[str,list,tuple], version = None, project_folder = None ):
    if isinstance( data, str ):
        writer( filedata.format( version = version, project_folder = project_folder ) )

    elif isinstance( data, (tuple,list) ):
        for line in data:
            writer( line.format( version = version, project_folder = project_folder ) )
            if not line.endswith( '\n' ):
                writer( '\n' )

    return


def createDefaults( target: str , version: int, project_folder, overwrite = False ):
    for filename, filedata in TEMPLATES.items():
        if not overwrite and os.path.exists( os.path.join( target, filename ) ):
            raise FileExistsError( os.path.exists( os.path.join( target, filename ) ) )

        print( f"Writing {target}/{filename}" )
        with open( os.path.join( target, filename ), 'w' ) as stream:
            __writeFileData( stream.write, filedata, version = version, project_folder = project_folder )

    return


def createExample( target: str, overwrite = False ):
    print( f"Writing {target}" )
    if not overwrite and os.path.exists( target ):
        raise FileExistsError( target )

    with open( target, 'w' ) as stream:
        __writeFileData( stream.write, EXAMPLE_TEMPLATE )

    return


def install( version: int ):
    currentDir = os.curdir
    print( 'Creating templates folder' )
    currentDir = os.path.join( currentDir, 'templates' )
    overwrite = False
    if os.path.exists( currentDir ):
        result = input( f"Folder '{currentDir}' allready exists, overwrite? (y/N)" )
        if result in ( "Y", "y" ):
            overwrite = True

        else:
            raise SystemExit()

        print( "" )

    if not overwrite:
        os.mkdir( currentDir )

    for dir in ( 'defaults', f'gencrud-v{version}'):
        print( f'Creating templates/{dir} folder' )
        if not os.path.exists( os.path.join( currentDir, dir ) ):
            os.mkdir( os.path.join( currentDir, dir ) )

    templateFolder = os.path.abspath( os.path.join( os.path.dirname( __file__ ), 'templates' ) )
    copyTemplates( os.path.join( templateFolder, f'gencrud-v{version}' ),
                   os.path.join( currentDir, f'gencrud-v{version}' ), overwrite = overwrite )
    createDefaults( os.path.join( currentDir, 'defaults' ), version, os.curdir, overwrite = overwrite )
    createExample( os.path.join( currentDir, 'example-application.templ' ), overwrite = overwrite )
    return


TEMPLATES = {
    'defaults.yaml': [
        "source:",
        "    base:                           {project_folder}",
        "    python:                         .",
        "    angular:                        frontend-v{version}/src/app",
        "templates:",
        "    base:                           {project_folder}/gencrud/templates-v{version}",
        "    python:                         python",
        "    angular:                        angular",
        "    common:",
        "        base:                       {project_folder}/gencrud/common/templates-v{version}",
        "        python:                     python",
        "        angular:                    angular",
        "options:",
        "    ignore-case-db-ids:             true",
        "    overwrite:                      true",
        "    use-module:                     true",
        "    generate-tests:                 false",
        "references:",
        "    app-module:",
        "        filename:                   app.module.ts",
        "        class:                      AppModule",
        "        module:                     app.module.ts",
        "    app-routing:",
        "        filename:                   app.routingmodule.ts",
        "        class:                      AppRoutingModule",
        "        module:                     app.routingmodule.ts" ],

    'action-no-add.yaml': [
        "# This file may be included in an application component template file for the add action to be disabled",
        "name:                 new",
        "type:                 none",
        "position:             none" ],

    'action-no-edit.yaml': [
        "# This file may be included in an application component template file for the edit action to be disabled",
        "name:                 edit",
        "type:                 none",
        "position:             none" ],

    'action-no-delete.yaml': [
        "# This file may be included in an application component template file for the delete action to be disabled",
        "name:                 delete",
        "type:                 none",
        "position:             none" ],

    'action-default-add.yaml': [
        "# This file may be included in an application component template file for the add action",
        "name:                 new",
        "label:                New",
        "type:                 screen",
        "icon:                 add",
        "position:             header",
        "function:             self.addRecord()" ],

    'action-default-edit.yaml': [
        "# This file may be included in an application component template file for the edit action",
        "name:                 new",
        "label:                New",
        "type:                 screen",
        "icon:                 add",
        "position:             header",
        "function:             self.editRecord( idx, row )" ],

    'action-default-delete.yaml': [
        "# This file may be included in an application component template file for the delete action",
        "name:                 new",
        "label:                New",
        "type:                 screen",
        "icon:                 add",
        "position:             header",
        "function:             self.deleteRecord( idx, row )" ],
}


EXAMPLE_TEMPLATE = [
    "#!gencrud",
    "version:                        2",
    "defaults:                       !include include/defaults-webapp.yaml",
    "application:                    webapp.backend",
    "objects:",
    "-   name:                       user",
    "    title:                      User",
    "    class:                      User",
    "    uri:                        /api/webapp/user",
    "    menu:",
    "    -   caption:                Administration",
    "        access:",
    "        -                       admin",
    "        -                       user-access",
    "        icon:                   library_books",
    "        # Add menu at the END",
    "        before:                 null",
    "        after:                  null",
    "        menu:",
    "        -   caption:            Users, Roles and Access",
    "            access:",
    "            -                   admin",
    "            -                   user-access",
    "            icon:               library_books",
    "            # Add the menu at the TOP",
    "            before:             *",
    "            after:              *",
    "            menu:",
    "            -   caption:        Users",
    "                access:",
    "                -               admin",
    "                -               user-access",
    "                icon:           library_books",
    "                # Add the menu at the TOP",
    "                before:         *",
    "                after:          *",
    "                route:          /user",
    "    route:                      /user",
    "    -   !include                include/default-action-add.yaml",
    "    -   !include                include/default-action-edit.yaml",
    "    -   name:                   delete",
    "        label:                  Delete",
    "        type:                   dialog",
    "        icon:                   delete",
    "        position:               cell",
    "        function:               core.deleteRecord( idx, row, 'U_ID', 'User', 'U_NAME'  )",
    "    table:",
    "        name:                   USER",
    "        columns:",
    "        -   field:",
    "                name:           U_ID",
    "                type:           INT",
    "                attribute:",
    "                -   AUTO NUMBER",
    "                -   PRIMARY KEY",
    "        -   field:",
    "                name:           U_ACTIVE",
    "                type:           BOOLEAN",
    "                attribute:      DEFAULT 0",
    "            label:              Active",
    "            ui:",
    "                type:           checkbox",
    "        -   field:",
    "                name:           U_NAME",
    "                type:           CHAR( 30 )",
    "                attribute:      NOT NULL",
    "            unique:             true",
    "            label:              Username",
    "            ui:",
    "                type:           textbox",
    "            listview:",
    "                index:          0",
    "                width:          20%",
    "        -   field:",
    "                name:           U_R_ID",
    "                type:           INT",
    "                foreignkey:     roles.r_id",
    "                attribute:      NOT NULL",
    "            label:              Role",
    "            ui:",
    "                type:           choice",
    "                service:",
    "                    name:       role",
    "                    class:      Role",
    "                    label:      R_NAME",
    "                    value:      R_ID",
    "            listview:",
    "                index:          1",
    "                width:          20%",
    "        -   field:",
    "                name:           U_HASH_PASSWORD",
    "                type:           CHAR( 255 )",
    "                attribute:      NULL",
    "            frontend:           false",
    "        -   field:",
    "                name:           U_LAST_LOGIN",
    "                type:           DATATIME",
    "                attribute:      NULL",
    "            readonly:           true",
    "            label:              Last login",
    "            ui:",
    "                type:           label",
    "                format:         %Y-%m-%d %H:%M:%S",
    "        -   field:",
    "                name:           U_PASSWD_TRIES",
    "                type:           INT",
    "                attribute:      DEFAULT 0",
    "            frontend:           false",
    "        -   field:",
    "                name:           U_FIRST_NAME",
    "                type:           CHAR( 50 )",
    "                attribute:      NOT NULL",
    "            label:              First name",
    "            ui:",
    "                type:           textbox",
    "            listview:",
    "                index:          2",
    "                width:          20%",
    "        -   field:",
    "                name:           U_MIDDLE_NAME",
    "                type:           CHAR( 50 )",
    "                attribute:      NULL",
    "            label:              Middle name(s)",
    "            ui:",
    "                type:           textbox",
    "        -   field:",
    "                name:           U_LAST_NAME",
    "                type:           CHAR( 50 )",
    "                attribute:      NOT NULL",
    "            label:              Surname",
    "            ui:",
    "                type:           textbox",
    "            listview:",
    "                index:          3",
    "                width:          20%",
    "        -   field:",
    "                name:           U_EMAIL",
    "                type:           CHAR( 100 )",
    "                attribute:      NOT NULL",
    "            label:              E-Mail",
    "            unique:             true",
    "            ui:",
    "                type:           textbox",
    "                validator:      email",
    "            listview:",
    "                index:          4",
    "                width:          20%",
    "        -   field:",
    "                name:           U_REMARK",
    "                type:           CLOB",
    "                attribute:      NULL",
    "            label:              Remark",
    "            ui:",
    "                type:           editor",
    "                attrubute:",
    "                    format:     markdown",
    "        -   field:",
    "                name:           U_LOCALE",
    "                type:           CHAR( 5 )",
    "                attribute:      DEFAULT 'en-GB'",
    "            ui:",
    "                type:           choice",
    "                resolvelist:",
    "                    en-GB:      en-GB",
    "                    de-DE:      de-DE",
    "                    fr-FR:      fr-FR",
    "                    it-IT:      it-IT",
    "                    nl-BE:      nl-BE",
    "                    nl-NL:      nl-NL",
    "        -   field:",
    "                name:           U_LISTITEMS",
    "                type:           INT",
    "                attribute:      DEFAULT 10",
    "            label:              List items",
    "            ui:",
    "                type:           choice",
    "                resolvelist:",
    "                    5:          5 items",
    "                    10:         10 items",
    "                    25:         25 items",
    "                    50:         50 items",
    "                    100:        100 items",
    "        -   field:",
    "                name:           U_PROFILE",
    "                type:           CLOB",
    "                attribute:      NULL",
    "            frontend:           false",
    "        -   field:",
    "                name:           U_JSON_DATA",
    "                type:           CLOB",
    "                attribute:      NULL",
    "            frontend:           false",
    "-   name:                       role",
    "    title:                      Role",
    "    class:                      Role",
    "    uri:                        /api/webapp/role",
    "    menu:",
    "    -   caption:                Administration",
    "        menu:",
    "        -   caption:            Users, Roles and Access",
    "            menu:",
    "            -   caption:        Roles",
    "                access:         admin,user-access",
    "                icon:           library_books",
    "                after:          Users",
    "                before:         Access",
    "                route:          /role",
    "    route:                      /role",
    "    -   !include                include/default-action-add.yaml",
    "    -   !include                include/default-action-edit.yaml",
    "    -   name:                   delete",
    "        label:                  Delete",
    "        type:                   dialog",
    "        icon:                   delete",
    "        position:               cell",
    "        function:               core.deleteRecord( idx, row, 'R_ID', 'Role', 'R_NAME'  )",
    "    table:",
    "        name:                   ROLE",
    "        columns:",
    "        -   field:",
    "                name:           R_ID",
    "                type:           INT",
    "                attribute:",
    "                -   AUTO NUMBER",
    "                -   PRIMARY KEY",
    "        -   field:",
    "                name:           R_NAME",
    "                type:           CHAR( 100 )",
    "                attribute:      NOT NULL",
    "            label:              Role",
    "            unique:             true",
    "            ui:",
    "                type:           text",
    "            listview:",
    "                index:          0",
    "                width:          50%",
    "        -   field:",
    "                name:           R_DEFAULT_CREATE",
    "                type:           BOOLEAN",
    "                attribute:      DEFAULT 0",
    "            label:              Create",
    "            ui:",
    "                type:           checkbox",
    "            listview:",
    "                index:          1",
    "                width:          10%",
    "        -   field:",
    "                name:           R_DEFAULT_READ",
    "                type:           BOOLEAN",
    "                attribute:      DEFAULT 0",
    "            label:              Read",
    "            ui:",
    "                type:           checkbox",
    "            listview:",
    "                index:          2",
    "                width:          10%",
    "        -   field:",
    "                name:           R_DEFAULT_UPDATE",
    "                type:           BOOLEAN",
    "                attribute:      DEFAULT 0",
    "            label:              Update",
    "            ui:",
    "                type:           checkbox",
    "            listview:",
    "                index:          3",
    "                width:          10%",
    "        -   field:",
    "                name:           R_DEFAULT_DELETE",
    "                type:           BOOLEAN",
    "                attribute:      DEFAULT 0",
    "            label:              Delete",
    "            ui:",
    "                type:           checkbox",
    "            listview:",
    "                index:          4",
    "                width:          10%",
    "        -   field:",
    "                name:           R_REMARK",
    "                type:           CLOB",
    "                attribute:      NULL",
    "            label:              Remark",
    "            ui:",
    "                type:           editor",
    "                attrubute:",
    "                    format:     markdown",
    "-   name:                       access",
    "    title:                      Access",
    "    class:                      Access",
    "    uri:                        /api/webapp/access",
    "    menu:",
    "    -   caption:                Administration",
    "        menu:",
    "        -   caption:            Users, Roles and Access",
    "            menu:",
    "            -   caption:        Access",
    "                access:",
    "                -               user-access",
    "                -               admin",
    "                icon:           library_books",
    "                # Add menyu after User and Role",
    "                before:         null",
    "                after:          Roles",
    "                route:          /access",
    "    route:                      /access",
    "    actions:",
    "    -   !include                include/default-action-add.yaml",
    "    -   !include                include/default-action-edit.yaml",
    "    -   name:                   delete",
    "        label:                  Delete",
    "        type:                   dialog",
    "        icon:                   delete",
    "        position:               cell",
    "        function:               core.deleteRecord( idx, row, 'A_ID', 'Access', 'A_COMPONENT'  )",
    "    table:",
    "        name:                   ACCESS",
    "        columns:",
    "        -   field:",
    "                name:           A_ID",
    "                type:           INT",
    "                attribute:",
    "                -   AUTO NUMBER",
    "                -   PRIMARY KEY",
    "        -   field:",
    "                name:           A_COMPONENT",
    "                type:           CHAR( 50 )",
    "                attribute:      NOT NULL",
    "            label:              Component",
    "            ui:",
    "                type:           textbox",
    "            listview:",
    "                index:          0",
    "                width:          40%",
    "        -   field:",
    "                name:           A_OBJECT",
    "                type:           INT",
    "                attribute:      DEFAULT 0",
    "            label:              Object type",
    "            ui:",
    "                type:           choice",
    "                resolvelist:",
    "                    1:          Menu",
    "                    2:          Table",
    "                    3:          Screen",
    "                    4:          Function",
    "        -   field:",
    "                name:           A_R_ID",
    "                type:           INT",
    "                foreignkey:     roles.r_id",
    "                attribute:      NULL",
    "            label:              Role",
    "            ui:",
    "                type:           choice",
    "                service:",
    "                    class:      Role",
    "                    name:       role",
    "                    label:      R_NAME",
    "                    value:      R_ID",
    "        -   field:",
    "                name:           A_CREATE",
    "                type:           BOOLEAN",
    "                attribute:      DEFAULT 0",
    "            label:              New/Create allowed",
    "            ui:",
    "                type:           checkbox",
    "        -   field:",
    "                name:           A_READ",
    "                type:           BOOLEAN",
    "                attribute:      DEFAULT 0",
    "            label:              Read allowed",
    "            ui:",
    "                type:           checkbox",
    "        -   field:",
    "                name:           A_UPDATE",
    "                type:           BOOLEAN",
    "                attribute:      DEFAULT 0",
    "            label:              Change/Update allowed",
    "            ui:",
    "                type:           checkbox",
    "        -   field:",
    "                name:           A_DELETE",
    "                type:           BOOLEAN",
    "                attribute:      DEFAULT 0",
    "            label:              Delete allowed",
    "            ui:",
    "                type:           checkbox",
    "        -   field:",
    "                name:           A_REMARK",
    "                type:           CLOB",
    "                attribute:      NULL",
    "            label:              Remark",
    "            ui:",
    "                type:           editor",
    "                attrubute:",
    "                    format:     markdown",
    "-   name:                       locking",
    "    title:                      Record locking",
    "    class:                      Locking",
    "    uri:                        /api/webapp/locking",
    "    menu:",
    "    -   caption:                Administration",
    "        menu:",
    "        -   caption:            Track and trace",
    "            access:             admin",
    "            menu:",
    "            -   caption:        Locking",
    "                access:         admin",
    "                icon:           library_books",
    "                # Add menu atr the TOP",
    "                before:         *",
    "                after:          *",
    "                route:          /locking",
    "    route:                      /locking",
    "    actions:",
    "    -   !include                include/no-action-add.yaml",
    "    -   !include                include/default-action-edit.yaml",
    "    -   name:                   delete",
    "        label:                  Delete",
    "        type:                   dialog",
    "        icon:                   delete",
    "        position:               cell",
    "        function:               core.deleteRecord( idx, row, 'L_ID', 'Locking', 'L_USER,L_TABLE'  )",
    "    table:",
    "        name:                   LOCKING",
    "        columns:",
    "        -   field:",
    "                name:           L_ID",
    "                type:           INT",
    "                attribute:",
    "                -   AUTO NUMBER",
    "                -   PRIMARY KEY",
    "        -   field:",
    "                name:           L_USER",
    "                type:           CHAR( 30 )",
    "                attribute:      NOT NULL",
    "            readonly:           true",
    "            label:              Username",
    "            ui:",
    "                type:           label",
    "            listview:",
    "                index:          0",
    "                width:          25%",
    "        -   field:",
    "                name:           L_TABLE",
    "                type:           CHAR( 128 )",
    "                attribute:      NOT NULL",
    "            readonly:           true",
    "            label:              Table name",
    "            ui:",
    "                type:           label",
    "            listview:",
    "                index:          1",
    "                width:          25%",
    "        -   field:",
    "                name:           L_RECORD_ID",
    "                type:           INT",
    "                attribute:      NOT NULL",
    "            readonly:           true",
    "            label:              Record ID",
    "            ui:",
    "                type:           number",
    "            listview:",
    "                index:          2",
    "                width:          25%",
    "        -   field:",
    "                name:           L_START_DATE",
    "                type:           DATETIME",
    "                attribute:      NOT NULL",
    "            readonly:           true",
    "            label:              Username",
    "            ui:",
    "                type:           label",
    "                format:         %Y-%m-%d %H:%M:%S",
    "            listview:",
    "                index:          3",
    "                width:          25%",
    "-   name:                       tracking",
    "    title:                      Modification tracking",
    "    class:                      Tracking",
    "    uri:                        /api/webapp/tracking",
    "    menu:",
    "    -   caption:                Administration",
    "        menu:",
    "        -   caption:            Track and trace",
    "            access:             admin",
    "            menu:",
    "            -   caption:        tracking",
    "                icon:           library_books",
    "                access:         admin",
    "                # Add menu atr the TOP",
    "                before:         *",
    "                after:          *",
    "                route:          /tracking",
    "    route:                      /tracking",
    "    mixin:",
    "        python:",
    "            view:",
    "                class:          TrackingMixin",
    "                filename:       mixin",
    "        angular:",
    "            table:",
    "                class:          TrackingMixin",
    "                filename:       mixin",
    "    actions:",
    "    -   !include                include/no-action-add.yaml",
    "    -   !include                include/default-action-edit.yaml",
    "    -   !include                include/no-action-delete.yaml",
    "    -   name:                   restore",
    "        label:                  Restore",
    "        type:                   dialog",
    "        icon:                   restore",
    "        position:               cell",
    "        function:               self.restoreRecord( idx, row, 'L_ID', 'L_USER,L_TABLE, T_ACTION' )",
    "    table:",
    "        name:                   TRACKING",
    "        columns:",
    "        -   field:",
    "                name:           T_ID",
    "                type:           INT",
    "                attribute:",
    "                -   AUTO NUMBER",
    "                -   PRIMARY KEY",
    "        -   field:",
    "                name:           T_USER",
    "                type:           CHAR( 30 )",
    "                attribute:      NOT NULL",
    "            readonly:           true",
    "            label:              Username",
    "            ui:",
    "                type:           label",
    "            listview:",
    "                index:          0",
    "                width:          20%",
    "        -   field:",
    "                name:           T_TABLE",
    "                type:           CHAR( 128 )",
    "                attribute:      NOT NULL",
    "            readonly:           true",
    "            label:              Table",
    "            ui:",
    "                type:           label",
    "            listview:",
    "                index:          2",
    "                width:          20%",
    "        -   field:",
    "                name:           T_ACTION",
    "                type:           INT",
    "                attribute:      NOT NULL",
    "            readonly:           true",
    "            label:              Action",
    "            ui:",
    "                type:           choice",
    "                resolvelist:",
    "                    1:          Insert",
    "                    2:          Update",
    "                    3:          Delete",
    "            listview:",
    "                index:          3",
    "                width:          10%",
    "        -   field:",
    "                name:           T_RECORD_ID",
    "                type:           INT",
    "                attribute:      NOT NULL",
    "            readonly:           true",
    "            label:              Record ID",
    "            ui:",
    "                type:           number",
    "            listview:",
    "                index:          4",
    "                width:          10%",
    "        -   field:",
    "                name:           T_RECORD_NAME",
    "                type:           CLOB",
    "                attribute:      NULL",
    "            readonly:           true",
    "            label:              Record Name",
    "            ui:",
    "                type:           label",
    "            listview:",
    "                index:          5",
    "                width:          20%",
    "        -   field:",
    "                name:           T_CHANGE_DATE_TIME",
    "                type:           DATETIME",
    "                attribute:      NOT NULL",
    "            readonly:           true",
    "            label:              Date & time",
    "            ui:",
    "                type:           label",
    "                format:         %Y-%m-%d %H:%M:%S",
    "            listview:",
    "                index:          1",
    "                width:          20%",
    "        -   field:",
    "                name:           T_CONTENTS",
    "                type:           CLOB",
    "                attribute:      NULL",
    "            frontend:           false",
    "        -   field:",
    "                name:           T_VERSION",
    "                type:           TEXT",
    "                attribute:      NOT NULL",
    "            readonly:           true",
    "            label:              Database version",
    "            ui:",
    "                type:           label",
    "            listview:",
    "                index:          6",
    "                width:          20%" ]