from applic.database import db
from sqlalchemy.orm import relationship

class User( db.Model ):
    """Model for the user table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    __tablename__       = 'WA_USERS'
    D_USER_ID = db.Column( Integer, autoincrement = True, primary_key = True)
    D_USER_NAME = db.Column( String( 20 ))
    D_PASSWORD = db.Column( String( 64 ))
    D_FIRST_NAME = db.Column( String( 30 ))
    D_MIDDLE_NAME = db.Column( String( 30 ))
    D_LAST_NAME = db.Column( String( 30 ))
    D_ROLE_ID = db.Column( Integer, ForeignKey( "WA_ROLES.D_ROLE_ID" ))
    ROLE = relationship( "RELATION"Role)

