from applic.extensions import mm
from testrun.user.model import User

class UserSchema( mm.ModelSchema ):
    """Schema for the user table, this is generated by the gencrud.py module
    When modifing the file make sure that you remove the table from the configuration.
    """
    class Meta:
        model = User

userSchema   = UserSchema()
usersSchema  = UserSchema( many = True )
