#
#   Python backend and Angular frontend code generation by gencrud
#   Copyright (C) 2018 Marc Bertens-Nguyen m.bertens@pe2mbs.nl
#
#   This library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU Library General Public License GPL-2.0-only
#   as published by the Free Software Foundation; either version 2 of the
#   License, or (at your option) any later version.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License GPL-2.0-only along with this library; if not, write to the
#   Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301 USA
#
#   Frontend view for the ${ obj.name } table, this is generated by the
#   gencrud.py module. When modifing the file make sure that you remove
#   the table from the configuration.
#
class TemplateMenuItem( object ):
    def __init__( self, key, **cfg ):
        self.__item = cfg[ key ]

    @property
    def index( self ):
        if 'index' in self.__item:
            return self.__item[ 'index' ]

        return -1

    @property
    def displayName( self ):
        return self.__item[ 'displayName' ]

    @property
    def iconName( self ):
        return self.__item[ 'iconName' ]

    @property
    def route( self ):
        if 'route' in self.__item:
            return self.__item[ 'route' ]

        return self.__item[ 'displayName' ]

    @property
    def menu( self ):
        if 'menu' in self.__item:
            return TemplateMenuItem( 'menu', **self.__item )

        return None