/*
*   Do not edit this file, this file is generated by the gencrud.py module
*/
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material';
import { Component, Inject } from '@angular/core';
import { FormControl, Validators, FormGroup } from '@angular/forms';
import { BaseDialog } from '../../common/dialog';
import { UserDataService } from './service';


@Component({
    selector: 'app-user-addedit-dialog',
    templateUrl: './addedit.dialog.html',
    styleUrls: ['../../common/dialog.scss']
})
export class AddEditUserDialog extends BaseDialog
{
    constructor( dialogRef: MatDialogRef<AddEditUserDialog>,
                 @Inject( MAT_DIALOG_DATA ) public data: any, 
                 dataService: UserDataService )
    { 
        super( dialogRef, dataService, data.mode );
        if ( !this.isEditMode() )
        {
            data.id = 'New';
        }
        this.formGroup = new FormGroup( {
            D_USER_ID: new FormControl( data.record.D_USER_ID,
                                              [  ] ),
            D_USER_NAME: new FormControl( data.record.D_USER_NAME,
                                              [ Validators.maxLength( 20 ),  ] ),
            D_PASSWORD: new FormControl( data.record.D_PASSWORD,
                                              [ Validators.maxLength( 64 ),  ] ),
            D_FIRST_NAME: new FormControl( data.record.D_FIRST_NAME,
                                              [ Validators.maxLength( 30 ),  ] ),
            D_MIDDLE_NAME: new FormControl( data.record.D_MIDDLE_NAME,
                                              [ Validators.maxLength( 30 ),  ] ),
            D_LAST_NAME: new FormControl( data.record.D_LAST_NAME,
                                              [ Validators.maxLength( 30 ),  ] ),
            D_ROLE_ID: new FormControl( data.record.D_ROLE_ID,
                                              [  ] ),
            ROLE: new FormControl( data.record.ROLE,
                                              [  ] ),
        } );
        return;
    }

    public get D_USER_ID()
    {
        return ( this.formGroup.get( 'D_USER_ID' ) );
    }

    public get D_USER_NAME()
    {
        return ( this.formGroup.get( 'D_USER_NAME' ) );
    }

    public get D_PASSWORD()
    {
        return ( this.formGroup.get( 'D_PASSWORD' ) );
    }

    public get D_FIRST_NAME()
    {
        return ( this.formGroup.get( 'D_FIRST_NAME' ) );
    }

    public get D_MIDDLE_NAME()
    {
        return ( this.formGroup.get( 'D_MIDDLE_NAME' ) );
    }

    public get D_LAST_NAME()
    {
        return ( this.formGroup.get( 'D_LAST_NAME' ) );
    }

    public get D_ROLE_ID()
    {
        return ( this.formGroup.get( 'D_ROLE_ID' ) );
    }

    public get ROLE()
    {
        return ( this.formGroup.get( 'ROLE' ) );
    }


    onSaveClick(): void
    {
        console.log( "AddEditUserDialog.onSaveClick() => ", this.formGroup.value );
        this.dataService.updateRecord( this.formGroup.value );
        super.onSaveClick();
        return;
    }
}

