/*
*   Do not edit this file, this file is generated by the gencrud.py module
*/

import { CrudDataSource } from '../../common/crud-datasource';
import { UserRecord } from './model';

export class UserDataSource extends CrudDataSource<UserRecord>
{
    sortActive( active: string, a: any, b: any ) : string[] 
    {
        switch ( active ) 
        {
        case 'D_USER_ID':
            return ( [ a.D_USER_ID, b.D_USER_ID ] );
        case 'D_USER_NAME':
            return ( [ a.D_USER_NAME, b.D_USER_NAME ] );
        case 'D_FIRST_NAME':
            return ( [ a.D_FIRST_NAME, b.D_FIRST_NAME ] );
        case 'D_MIDDLE_NAME':
            return ( [ a.D_MIDDLE_NAME, b.D_MIDDLE_NAME ] );
        case 'D_LAST_NAME':
            return ( [ a.D_LAST_NAME, b.D_LAST_NAME ] );
        }
        return ( [ null, null ] );        
    }
}


