/*
*   Do not edit this file, this file is generated by the gencrud.py module
*/
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material';
import { Component, Inject } from '@angular/core';
import { BaseDialog } from '../../common/dialog';
import { UserDataService } from './service'

@Component({
    selector: 'app-user-delete-dialog',
    templateUrl: './delete.dialog.html',
    styleUrls: ['../../common/dialog.scss']
})
export class DeleteUserDialog extends BaseDialog
{
    constructor( dialogRef: MatDialogRef<DeleteUserDialog>,
                 @Inject( MAT_DIALOG_DATA ) public data: any, 
                 dataService: UserDataService )
    { 
        super( dialogRef, dataService )
        return;
    }

    onCancelClick(): void 
    {
        this.dialogRef.close();
        return;
    }

    onSaveClick(): void 
    {
        this.dataService.deleteRecord( this.data.record );
        return;
    }
}

