/*
*   Do not edit this file, this file is generated by the gencrud.py module
*/
import { RoleRecord } from '../../testrun/role/model'

export class UserRecord
{
    D_USER_ID: number;
    D_USER_NAME: string;
    D_PASSWORD: string;
    D_FIRST_NAME: string;
    D_MIDDLE_NAME: string;
    D_LAST_NAME: string;
    D_ROLE_ID: number;
    ROLE: RoleRecord;
}

