/*
*   Do not edit this file, this file is generated by the gencrud.py module
*/
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CrudDataService } from '../../common/crud-dataservice';
import { UserRecord } from './model';


@Injectable()
export class UserDataService extends CrudDataService<UserRecord>
{
    constructor ( httpClient: HttpClient ) 
    {
        super( httpClient );
        this.uri = /api/user;
        return;
    }
}

