/*
*   Do not edit this file, this file is generated by the gencrud.py module
*/
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material';
import { Component, Inject } from '@angular/core';
import { FormControl, Validators, FormGroup } from '@angular/forms';
import { BaseDialog } from '../../common/dialog';
import { RoleDataService } from './service';


@Component({
    selector: 'app-role-addedit-dialog',
    templateUrl: './addedit.dialog.html',
    styleUrls: ['../../common/dialog.scss']
})
export class AddEditRoleDialog extends BaseDialog
{
    constructor( dialogRef: MatDialogRef<AddEditRoleDialog>,
                 @Inject( MAT_DIALOG_DATA ) public data: any, 
                 dataService: RoleDataService )
    { 
        super( dialogRef, dataService, data.mode );
        if ( !this.isEditMode() )
        {
            data.id = 'New';
        }
        this.formGroup = new FormGroup( {
            D_ROLE_ID: new FormControl( data.record.D_ROLE_ID,
                                              [  ] ),
            D_ROLE: new FormControl( data.record.D_ROLE,
                                              [ Validators.maxLength( 20 ),  ] ),
            USERS: new FormControl( data.record.USERS,
                                              [  ] ),
        } );
        return;
    }

    public get D_ROLE_ID()
    {
        return ( this.formGroup.get( 'D_ROLE_ID' ) );
    }

    public get D_ROLE()
    {
        return ( this.formGroup.get( 'D_ROLE' ) );
    }

    public get USERS()
    {
        return ( this.formGroup.get( 'USERS' ) );
    }


    onSaveClick(): void
    {
        console.log( "AddEditRoleDialog.onSaveClick() => ", this.formGroup.value );
        this.dataService.updateRecord( this.formGroup.value );
        super.onSaveClick();
        return;
    }
}

