/*
*   Do not edit this file, this file is generated by the gencrud.py module
*/

import { CrudDataSource } from '../../common/crud-datasource';
import { RoleRecord } from './model';

export class RoleDataSource extends CrudDataSource<RoleRecord>
{
    sortActive( active: string, a: any, b: any ) : string[] 
    {
        switch ( active ) 
        {
        case 'D_ROLE_ID':
            return ( [ a.D_ROLE_ID, b.D_ROLE_ID ] );
        case 'D_ROLE':
            return ( [ a.D_ROLE, b.D_ROLE ] );
        }
        return ( [ null, null ] );        
    }
}


