/*
*   Do not edit this file, this file is generated by the gencrud.py module
*/
import { UserRecord } from '../../testrun/user/model'

export class RoleRecord
{
    D_ROLE_ID: number;
    D_ROLE: string;
    USERS: UserRecord;
}

