/*
*   Do not edit this file, this file is generated by the gencrud.py module
*/

import { async, ComponentFixture, TestBed } from '@angular/core/testing';

import { RoleTableComponent } from './table.component';

describe('CrudTableComponent', () => {
    let component: RoleTableComponent;
    let fixture: ComponentFixture<RoleTableComponent>;

    beforeEach(async(() => {
        TestBed.configureTestingModule( {
            declarations: [ RoleTableComponent ]
        } ).compileComponents();
    } ) );

    beforeEach(() => {
        fixture = TestBed.createComponent( RoleTableComponent );
        component = fixture.componentInstance;
        fixture.detectChanges();
    } );

    it( 'should create', () => {
        expect( component ).toBeTruthy();
    } );
} );

